---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring-dependencies:
        patterns:
          - "org.springframework.*"
          - "org.springframework.boot.*"
          - "org.springframework.cloud.*"
    ignore:
      - dependency-name: "org.springframework.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.boot.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.springframework.cloud.*"
        update-types: ["version-update:semver-major"]
